### ISSUE TITLE
UI API called on a background thread

### ISSUE THREAD

**Issue by PahlevanyanSamvel** [jwplayer/jwplayer-sdk-ios-demo#71]
Hi dear support team, 
I have updated iOS 13 and SDK become with errors .
Please look and let me know if any ida

<img width="727" alt="Screen Shot 2019-09-30 at 7 04 45 PM" src="https://user-images.githubusercontent.com/34054539/65891192-32a87f80-e3b5-11e9-87f2-3e1a3428f9f2.png">

**Comment by karimMourra** [comment]
Hi @PahlevanyanSamvel , which version of our SDK are you using ? I believe this issue was fixed several versions ago. Our latest version is 3.6.3 and 3.7.0 is on the way.

**Comment by PahlevanyanSamvel** [comment]
Maybe 3.5,
I will check it, thank you very much.

**Comment by PahlevanyanSamvel** [comment]
Hi dear  @karimMourra , I am using 3.6.3 version but the issue is still actual.

<img width="1051" alt="Screen Shot 2019-10-01 at 10 57 30 AM" src="https://user-images.githubusercontent.com/34054539/65940731-48ac5380-e43a-11e9-9f9e-cb18a8383186.png">

**Comment by karimMourra** [comment]
@PahlevanyanSamvel thank you! We are looking into the issue. I will keep you posted

**Comment by karimMourra** [comment]
@PahlevanyanSamvel the issue was fixed and will be released with version 3.7.0 which is scheduled to go out on thursday
